# Generated by Django 4.1.1 on 2022-09-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_category_news_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="news.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
